### ISSUE TITLE
Enlace quebrado en descripcion

### ISSUE THREAD

**Issue by mcpollo** [ventanita/ventanita#55]
En la sección Objetivo Principal se hace referencia al sitio

http://www.selallevanfacil.info/home/ 

pero retorna un 404. Si el sitio realmente no existe, que tal usar la copia en wayback machine

https://web.archive.org/web/20131125011350/http://www.selallevanfacil.info/home/

para que quienes no conozcan el sitio puedan entender la referencia.

**Comment by aniversarioperu** [comment]
gracias @mcpollo. He preguntado a la gente del @utero y parece que por ahora no estará disponible **selallevanfacil.info** Podemos usar el link hacia wayback machine.

Te animas a hacer un pull request?

**Comment by mcpollo** [comment]
Listo. Aún no me acostumbro a github, así que el pull request tiene un commit de más :-)

**Comment by aniversarioperu** [comment]
gracias!, cerrado con #57
