### ISSUE TITLE
escrapear datos de la SUTRAN, multas

### ISSUE THREAD

**Issue by aniversarioperu** [ventanita/ventanita#69]
Multas, sutran:
http://www.sutran.gob.pe/portal/index.php/devolucion-licencias-de-conducir-pnp

**Comment by escribiendocodigo** [comment]
Buenas me gustaria contribuir, pero tengo algunas dudas:

¿la data extraida se debe volcar a alguna tabla y cual es la estructura que debo seguir?
¿implementarlo como una API Restful?

**Comment by aniversarioperu** [comment]
hola @escribiendocodigo 

Los datos extraídos pueden ser guardados por el software en tabla TSV (separada por tabs). También puede ser en formaton JSON.

Luego de extraer los datos, es posible que se necesiten limpiar y normalizar. Luego serán incoportados en la base de datos PostgreSQL de <http://github.com/ventanita/ventanita>. Lo más probable es que tengamos que crearle una tabla para la info que genere este scraper.

Estamos explorando la posibilidad de usar protocol buffer para la ruta entre limpieza de datos y base de datos. Pero eso será luego. Es suficiente que este scraper emita en TSV o JSON.

**Comment by escribiendocodigo** [comment]
ok

**Comment by escribiendocodigo** [comment]
Listo
https://github.com/escribiendocodigo/scraper_sutran

**Comment by aniversarioperu** [comment]
qué chévere! le voy a hacer un fork. Gracias!

**Comment by aniversarioperu** [comment]
aquí el fork https://github.com/ventanita/scraper_sutran. Cierro este *issue*.
